### ISSUE TITLE
Time formatting

### ISSUE THREAD

**Issue by shrimpza** [shrimpza/utstatsdb#1]
Times currently displayed in format: 

> 4.5

This would probably be more informatively displayed as: 

> 4m30s

**Comment by Suharsh329** [comment]
```PHP
$hours = floor($time / 60);
$minutes = $time % 60;
$seconds = floor(($time - floor($time)) * 60);
```

**Comment by shrimpza** [comment]
Pages which need attention:

- [x] Index
- [x] Match list
- [x] Match details
- [x] Match player
- [x] Player list
- [x] Player details
- [x] Maps list
- [x] Map details
- [x] Servers list
- [x] Server details
- [x] Totals
- [x] Career highs
- [x] Match highs

**Comment by ddormer** [comment]
👍
